-- Run this in your Supabase SQL editor

create table projects (
  id bigint generated by default as identity primary key,
  title text not null,
  category text,
  youtube_id text not null,
  thumbnail_url text,
  sort_order int default 0,
  created_at timestamptz default now()
);

-- Enable public read access (no auth needed for portfolio)
alter table projects enable row level security;

create policy "Public read" on projects
  for select using (true);

-- Example rows — replace youtube_id with your real video IDs
insert into projects (title, category, youtube_id, sort_order) values
  ('Film Title One', 'Film', 'YOUR_YT_ID_1', 1),
  ('Commercial Title', 'Commercial', 'YOUR_YT_ID_2', 2),
  ('Music Video Title', 'Music Video', 'YOUR_YT_ID_3', 3);
